# Generated by Django 6.0.7 on 2026-09-22 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_remindernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='last_registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
