# Generated by Django 6.0.7 on 2026-08-31 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_account'),
        ('transactions', '0002_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='loan_transaction_type',
            field=models.CharField(blank=True, choices=[('initial', 'Initial Loan'), ('repayment', 'Loan Repayment')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('loan', 'Loan')], max_length=20),
        ),
    ]
