# Generated by Django 6.0.7 on 2026-09-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20, unique=True)),
                ('latest_version', models.CharField(max_length=20)),
                ('minimum_version', models.CharField(max_length=20)),
                ('update_url', models.URLField(blank=True)),
                ('force_update', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
